---
image: natanfelles/php-base

test:php7.3:
  stage: test
  cache:
    paths:
      - vendor/
  services:
    - mariadb
    - memcached
    - redis
  variables:
    MYSQL_DATABASE: framework-tests
    MYSQL_ROOT_PASSWORD: password
  before_script:
    - composer install
  script:
    # composer.json normalization
    - composer normalize --dry-run --indent-size=1 --indent-style=tab
    # Check if syntax errors was fixed with php-cs-fixer
    - vendor/bin/php-cs-fixer fix --diff --dry-run --verbose
    # Analyse code with PHPStan
    # - vendor/bin/phpstan analyse
    # PHPMD
    # - vendor/bin/phpmd src/ text phpmd.xml
    # - vendor/bin/phpmd tests/ text phpmd.xml
    # Run PHPUnit
    - vendor/bin/phpunit --colors=never
    # ApiGen
    # - vendor/bin/apigen generate App.php app --destination build/api/
  artifacts:
    paths:
      - build/coverage/
      # - build/api/
  coverage: '/^\s*Lines:\s*\d+.\d+\%/'

pages:
  stage: deploy
  dependencies:
    - test:php7.3
  environment:
    name: production
    url: https://the-framework.gitlab.io
  script:
    - mv public/ app-public/
    - mkdir public/
    - mv build/coverage/ public/
    # - mv build/api/ public/
    - curl -sS https://the-framework.gitlab.io/redirect.php | php
    - 'curl --request POST --header "PRIVATE-TOKEN: $BUILD_TOKEN" "https://gitlab.com/api/v4/projects/11395127/pipeline?ref=master"'
  artifacts:
    paths:
      - public
  only:
    - master
