version: "3.0"
services:
  lempa:
    image: registry.gitlab.com/aplus-framework/images/lempa:2
    container_name: lempa-app
    working_dir: /var/www/aplus
    volumes:
      - .:/var/www/aplus
    ports:
      - "80:80"
      - "443:443"
    #environment:
    #  - PRELOAD=/var/www/aplus/preload.php
    tty: true
